# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - talktoloopv2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_955213cb9423492297b39dcc0f0431a3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c495f605deed49d18670294acc1e4f15 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_955213cb9423492297b39dcc0f0431a3 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'talktoloopv2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ab7694b4f21457ea7b2ac406694ce80 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_955213cb9423492297b39dcc0f0431a3 }}/appsvc/staticsite:${{ github.sha }}'